package com.crescendo.shared.domain.valueobject;

import jakarta.persistence.Embeddable;

/**
 * Value Object representing a unique device identifier.
 * Often generated by the client (e.g. UUID stored in localStorage).
 * Immutable and self-validating.
 */
@Embeddable
public record DeviceId(String value) {

    private static final int MAX_LENGTH = 128;

    public DeviceId {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("Device ID cannot be null or blank");
        }
        value = value.trim();
        if (value.length() > MAX_LENGTH) {
            throw new IllegalArgumentException("Device ID cannot exceed " + MAX_LENGTH + " characters");
        }
    }

    public static DeviceId of(String value) {
        if (value == null || value.isBlank()) return null;
        return new DeviceId(value);
    }

    @Override
    public String toString() {
        return value;
    }
}
