"""
Workflow Builder Router
=======================
Exposes:  POST /v1/workflow-drafts

Accepts requests proxied from the Java backend (WorkflowDraftController).
Validates the shared Bearer service token, then delegates to the planner agent.

Expected request body:
    {
      "userId":  "uuid-string",
      "prompt":  "NL workflow description",
      "context": { ...optional... }
    }

Expected response:
    {
      "success": true,
      "workflow_spec": { ... },
      "error": null
    }
"""

import os
import logging

from fastapi import APIRouter, Depends, HTTPException, Security, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from app.agents.planner import plan_workflow
from app.schemas.workflow import WorkflowDraftRequest, WorkflowDraftResponse
from app.security.sanitizer import sanitize_prompt

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/v1", tags=["workflow-drafts"])

# ---------------------------------------------------------------------------
# Auth — shared service token (Bearer)
# ---------------------------------------------------------------------------

_bearer_scheme = HTTPBearer(auto_error=True)


def _verify_service_token(
    credentials: HTTPAuthorizationCredentials = Security(_bearer_scheme),
) -> None:
    """
    Validates the incoming Bearer token against SERVICE_TOKEN env var.
    SERVICE_TOKEN is always required — the Java backend must be configured
    with crescendo.python-ai.service-token.
    """
    expected_token = os.getenv("SERVICE_TOKEN", "")
    if not expected_token:
        # Misconfiguration on the Python side — fail loudly
        logger.error("SERVICE_TOKEN env var is not set; all requests are rejected.")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI service is misconfigured (missing SERVICE_TOKEN).",
        )
    if credentials.credentials != expected_token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid service token.",
            headers={"WWW-Authenticate": "Bearer"},
        )


# ---------------------------------------------------------------------------
# Route
# ---------------------------------------------------------------------------

@router.post(
    "/workflow-drafts",
    response_model=WorkflowDraftResponse,
    summary="Generate a workflow draft from a natural-language prompt",
)
async def create_workflow_draft(
    request: WorkflowDraftRequest,
    _: None = Depends(_verify_service_token),
) -> WorkflowDraftResponse:
    """
    Accepts a natural-language prompt from an authenticated user (forwarded
    by the Java backend) and returns a structured WorkflowSpec generated by
    the Groq LLM planner.

    The `context` field may contain:
      - `connected_apps`     — list of apps the user has already connected
      - `existing_workflows` — names of workflows the user already has
      - any other key-value metadata to guide generation
    """
    logger.info("Received workflow draft request for user=%s", request.userId)

    # Sanitize user input — raises HTTP 400 if injection patterns are detected.
    # Returns the prompt wrapped in <user_request>…</user_request> delimiters.
    sanitized_prompt = sanitize_prompt(request.prompt)

    result = plan_workflow(
        prompt=sanitized_prompt,
        context=request.context,
        user_id=request.userId,
    )

    return result
