import { Link } from 'react-router-dom';
import './LegalPage.css';

export default function PrivacyPage() {
    return (
        <div className="legal-page">
            <nav className="legal-page-nav">
                <Link to="/" className="legal-nav-brand">Crescendo</Link>
                <span className="legal-nav-sep">/</span>
                <span className="legal-nav-title">Privacy Policy</span>
                <Link to="/" className="legal-nav-back">← Back to Home</Link>
            </nav>

            <div className="legal-container">
                <div className="legal-header">
                    <div className="legal-badge">Legal</div>
                    <h1 className="legal-title">Privacy Policy</h1>
                    <p className="legal-subtitle">
                        Your privacy matters to us. This policy explains what data we collect,
                        why we collect it, how we use it, and the choices you have.
                    </p>
                    <div className="legal-meta">
                        <span className="legal-meta-item">
                            <span className="legal-meta-dot" />
                            Effective: January 1, 2026
                        </span>
                        <span className="legal-meta-item">
                            <span className="legal-meta-dot" />
                            Last updated: March 1, 2026
                        </span>
                    </div>
                </div>

                <div className="legal-highlight-box">
                    <strong>Short version:</strong> We collect information you give us and data
                    generated by your use of the Service. We use it to operate, improve, and
                    secure Crescendo. We do not sell your personal data. You can request deletion
                    of your data at any time.
                </div>

                <div className="legal-content">
                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">1</span>
                            Who We Are
                        </h2>
                        <p>
                            Crescendo (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;)
                            operates the workflow automation platform available at our website and
                            associated services. We act as the data controller for personal
                            information we collect from users.
                        </p>
                        <p>
                            For questions about this policy, contact us at{' '}
                            <a href="mailto:privacy@crescendo.app" style={{ color: 'var(--text-accent, #fafafa)' }}>
                                privacy@crescendo.app
                            </a>.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">2</span>
                            Information We Collect
                        </h2>
                        <p>We collect the following categories of information:</p>
                        <ul>
                            <li>
                                <strong>Account information:</strong> Name, email address, and
                                password (hashed) when you register.
                            </li>
                            <li>
                                <strong>Profile information:</strong> Any optional profile details
                                you add to your account.
                            </li>
                            <li>
                                <strong>OAuth tokens:</strong> Access and refresh tokens for
                                third-party integrations you connect (e.g., Google, Microsoft,
                                Twitter). These are encrypted at rest.
                            </li>
                            <li>
                                <strong>Workflow data:</strong> Workflows, trigger/action
                                configurations, and execution history you create within the Service.
                            </li>
                            <li>
                                <strong>Email service data:</strong> Contacts, email templates,
                                broadcast campaigns, and delivery logs if you use our email
                                features.
                            </li>
                            <li>
                                <strong>Usage data:</strong> Log data, IP addresses, browser type,
                                pages visited, and interaction events to diagnose issues and improve
                                performance.
                            </li>
                            <li>
                                <strong>Cookies and local storage:</strong> Session identifiers and
                                preference tokens stored in your browser.
                            </li>
                        </ul>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">3</span>
                            How We Use Your Information
                        </h2>
                        <p>We use the information we collect to:</p>
                        <ul>
                            <li>Create and manage your account and authenticate your identity.</li>
                            <li>Operate the Service, including executing workflows on your behalf.</li>
                            <li>
                                Send transactional emails (e.g., email verification, password
                                reset, MFA codes).
                            </li>
                            <li>Provide customer support and respond to your inquiries.</li>
                            <li>
                                Monitor and improve the reliability, security, and performance of
                                the Service.
                            </li>
                            <li>
                                Detect, investigate, and prevent fraudulent transactions and
                                other illegal activities.
                            </li>
                            <li>
                                Comply with legal obligations and enforce our Terms of Service.
                            </li>
                        </ul>
                        <p>
                            We will not use your data for purposes materially different from those
                            stated above without obtaining your prior consent.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">4</span>
                            Third-Party Integrations and Data Sharing
                        </h2>
                        <p>
                            When you connect a third-party app (such as Google, Microsoft, or
                            Twitter/X), we receive OAuth tokens that allow us to interact with
                            that service on your behalf. We only request the minimum scopes
                            necessary to execute your configured workflows.
                        </p>
                        <p>We may share data with:</p>
                        <ul>
                            <li>
                                <strong>Infrastructure providers:</strong> Cloud hosting, database,
                                and caching services required to operate the platform (e.g., AWS,
                                Redis).
                            </li>
                            <li>
                                <strong>Email delivery providers:</strong> We use Brevo (formerly
                                Sendinblue) to deliver transactional emails on your behalf when
                                you use the email service feature.
                            </li>
                            <li>
                                <strong>Legal authorities:</strong> When required by applicable
                                law, court order, or governmental authority.
                            </li>
                        </ul>
                        <p>
                            We do not sell, rent, or trade your personal information to third
                            parties for their own marketing purposes.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">5</span>
                            Google User Data and Limited Use Policy
                        </h2>
                        <p>
                            Our application allows you to connect your Google account to automate workflows. We are committed to protecting your Google user data in compliance with Google's policies:
                        </p>
                        <ul>
                            <li><strong>What we collect:</strong> We collect and securely store your Google OAuth access and refresh tokens. Depending on the authorized scopes, the application may access your Google profile data, Google Sheets documents, or Gmail messages during workflow execution.</li>
                            <li><strong>How we use the data:</strong> We use your Google user data strictly to provide the workflow automation services you requested (e.g., reading a sheet row or sending an email). We do not use this data for training AI models.</li>
                            <li><strong>Data sharing:</strong> We do not transfer or disclose your Google user data to third parties for purposes other than providing or improving our application's functionality.</li>
                            <li><strong>No sale of data:</strong> We absolutely do not sell Google user data to third parties, data brokers, or information resellers. We do not use this data for targeted, personalized, or interest-based advertising.</li>
                            <li><strong>Data protection:</strong> Security procedures are in place to protect the confidentiality of your data. We use encryption to protect your Google user data both in transit and at rest.</li>
                            <li><strong>Retention and deletion:</strong> We retain your Google user data only for as long as your account is active and the integration is connected. You may disconnect your Google account to revoke access, or request account deletion, at which point all associated Google data and tokens will be permanently destroyed.</li>
                        </ul>
                        <p>
                            <strong>Limited Use:</strong> Crescendo's use and transfer to any other app of information received from Google APIs will adhere to the <a href="https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes" target="_blank" rel="noreferrer" style={{ color: 'var(--text-accent, #fafafa)' }}>Google API Services User Data Policy</a>, including the Limited Use requirements.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">6</span>
                            Data Retention
                        </h2>
                        <p>
                            We retain your personal data for as long as your account is active or
                            as needed to provide you the Service. Workflow execution history is
                            retained for up to 90 days by default, after which it is
                            automatically purged.
                        </p>
                        <p>
                            If you delete your account, we will delete or anonymize your personal
                            data within 30 days, except where we are required to retain it for
                            legal or compliance purposes.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">7</span>
                            Security
                        </h2>
                        <p>
                            We implement industry-standard security measures to protect your data,
                            including:
                        </p>
                        <ul>
                            <li>Encryption of data in transit using TLS.</li>
                            <li>Encryption of sensitive data (OAuth tokens) at rest.</li>
                            <li>Bcrypt hashing of passwords — we never store plaintext passwords.</li>
                            <li>Optional multi-factor authentication (MFA) for your account.</li>
                            <li>Regular security reviews and dependency audits.</li>
                        </ul>
                        <p>
                            No method of transmission or storage is 100% secure. If you believe
                            your account has been compromised, contact us immediately at{' '}
                            <a href="mailto:security@crescendo.app" style={{ color: 'var(--text-accent, #fafafa)' }}>
                                security@crescendo.app
                            </a>.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">8</span>
                            Cookies
                        </h2>
                        <p>
                            We use essential cookies and local storage for authentication
                            (session tokens) and user preferences (theme, layout state). We do
                            not use third-party advertising or tracking cookies.
                        </p>
                        <p>
                            You can clear cookies and local storage through your browser settings,
                            but doing so will log you out of the Service.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">9</span>
                            Your Rights
                        </h2>
                        <p>
                            Depending on your jurisdiction, you may have the following rights
                            regarding your personal data:
                        </p>
                        <ul>
                            <li>
                                <strong>Access:</strong> Request a copy of the personal data we
                                hold about you.
                            </li>
                            <li>
                                <strong>Correction:</strong> Request correction of inaccurate or
                                incomplete data.
                            </li>
                            <li>
                                <strong>Deletion:</strong> Request deletion of your personal data
                                (right to be forgotten).
                            </li>
                            <li>
                                <strong>Portability:</strong> Request your data in a
                                machine-readable format.
                            </li>
                            <li>
                                <strong>Objection:</strong> Object to processing of your data for
                                certain purposes.
                            </li>
                            <li>
                                <strong>Revoke consent:</strong> Disconnect any third-party
                                integrations at any time via the Connections settings page.
                            </li>
                        </ul>
                        <p>
                            To exercise any of these rights, email us at{' '}
                            <a href="mailto:privacy@crescendo.app" style={{ color: 'var(--text-accent, #fafafa)' }}>
                                privacy@crescendo.app
                            </a>.
                            We will respond within 30 days.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">10</span>
                            Children&rsquo;s Privacy
                        </h2>
                        <p>
                            The Service is not directed at children under the age of 13. We do not
                            knowingly collect personal information from children. If you believe we
                            have collected information from a child under 13, please contact us
                            immediately and we will delete it.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">11</span>
                            Changes to This Policy
                        </h2>
                        <p>
                            We may update this Privacy Policy from time to time. We will notify
                            you of material changes by sending an email to your registered address
                            and/or posting a notice in the application. The &ldquo;Last
                            updated&rdquo; date at the top of this page indicates when the policy
                            was last revised.
                        </p>
                        <p>
                            Continued use of the Service after changes become effective constitutes
                            acceptance of the revised policy.
                        </p>
                    </div>

                    <div className="legal-divider" />

                    <div className="legal-section">
                        <h2 className="legal-section-heading">
                            <span className="legal-section-number">12</span>
                            Contact Us
                        </h2>
                        <p>
                            For privacy-related questions, data requests, or to report a concern:
                        </p>
                        <div className="legal-contact-box">
                            <span className="contact-label">Privacy inquiries</span>
                            <a href="mailto:privacy@crescendo.app">privacy@crescendo.app</a>
                            <span className="contact-label" style={{ marginTop: 8 }}>Security issues</span>
                            <a href="mailto:security@crescendo.app">security@crescendo.app</a>
                            <span className="contact-label" style={{ marginTop: 8 }}>General support</span>
                            <a href="mailto:support@crescendo.app">support@crescendo.app</a>
                        </div>
                    </div>
                </div>

                <div className="legal-footer">
                    <span className="legal-footer-text">© 2026 Crescendo. All rights reserved.</span>
                    <div className="legal-footer-links">
                        <Link to="/privacy">Privacy Policy</Link>
                        <Link to="/terms">Terms of Service</Link>
                        <Link to="/">Home</Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
